[package]
name = "symbly"
version = "0.1.0"
authors = ["João Paulo Taylor Ienczak Zanette <jpaulotiz@gmail.com>"]
edition = "2018"

[dependencies]
structopt = { version = "0.2", default-features = false }
pest = "2.0"
pest_derive = "2.0"
